### ISSUE TITLE
How to perform sahi inference prediction on multiple images instead of videos and save the corresponding txt results?

### ISSUE THREAD

**Issue by ECHO967** [IrDIE/YOLO8_SAHI#1]
Thank you for your work. I noticed that the input video is in the prediction stage. My input is many images or maybe one image. Which part of your code should I modify in this case?

**Comment by IrDIE** [comment]
Hi, @ECHO967 
You can pass in `run_sahi_prediction(... , source=predict_source )` where `predict_source = './yolo_dataset/images'` - path to folder with images
if you still meet any problem feel free to ask :)

**Comment by IrDIE** [comment]
@ECHO967 
`save the corresponding txt results` - 
in `compile_predictor()` you can try add that line:
`args.save_txt = True`

but probably it wont work - check this - https://github.com/ultralytics/ultralytics/issues/2143
