### ISSUE TITLE
how to use the inputing image size 

### ISSUE THREAD

**Issue by echo385** [IrDIE/YOLO8_SAHI#2]
I want to use the input image size to prediction and evaluate, rather than the imgsz set by myself.  

def main():
    warnings.filterwarnings("ignore")
    # here set your parameters
    pt_model = './best.pt'
    yaml_datapath = './three_classes_data.yaml' # for validation
    **imgsz = 1280 # for sahi validation or prediction   ########### this imgsz**
    predict_source = './yolo_dataset/images'
    # video1_source = './1.mp4'

    # defaults params
    args = get_cfg(cfg=DEFAULT_CFG)
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    LOGGER.info(f'DEVICE ===>> {device}')

    # VALIDATION
    run_basic_validation(pt_model, yaml_datapath, args)
    run_sahi_validation(pt_model, yaml_datapath, args, imgsz, device)

**Comment by IrDIE** [comment]
Hi, @echo385 
Check out new version of that repo. I did some refactoring:
* now raw prediction  from sahi inference and usual-inference concatenated and passed in nms all together (more accurate prediction)
* and during prediction you can set imgsize = None - therefore original image size will be used for prediction

If you still face problems feel free to ask ❤️

**Comment by echo385** [comment]
> Hi, @echo385 Check out new version of that repo. I did some refactoring:
> 
> * now raw prediction  from sahi inference and usual-inference concatenated and passed in nms all together (more accurate prediction)
> * and during prediction you can set imgsize = None - therefore original image size will be used for prediction
> 
> If you still face problems feel free to ask ❤️


Thank you for your reply. If I want to use the original size of the image during verification, I will directly set it to None and get an error.

**Comment by IrDIE** [comment]
@echo385 
Yes. Now it's available for prediction only. 
Can you tell why you wanna use it during validation? I suppose you will not see significant difference in metrics if imgsize is large enough for your dataset.
And during validation with that feature ( original size for each image ) it's impossible to use batches - what is more time consuming...

btw I will add that feature for validation soon.

**Comment by echo385** [comment]
> @echo385 Yes. Now it's available for prediction only. Can you tell why you wanna use it during validation? I suppose you will not see significant difference in metrics if imgsize is large enough for your dataset. And during validation with that feature ( original size for each image ) it's impossible to use batches - what is more time consuming...
> 
> btw I will add that feature for validation soon.

thank you for your reply ! Because I want to implement the verification process and get evaluation indicators, such as the recall curve, on a picture with a resolution of 13000*12000. but I find that I can't get a target with a confidence level of 0 or even less than 0.25, so what modifications should I make?

**Comment by IrDIE** [comment]
@echo385 

Check out new version - `git pull`

now - if you pass `imgsz = None` in `main()` validation will be done with original image size.
Batch size will be forced to 1

**Comment by echo385** [comment]
> @echo385
> 
> Check out new version - `git pull`
> 
> now - if you pass `imgsz = None` in `main()` validation will be done with original image size. Batch size will be forced to 1

thank you for your commit! but I also have the same error when I use the new code.
![image](https://github.com/IrDIE/YOLO8_SAHI/assets/52439142/cf8b5032-4535-4627-b59a-361936af7455)
