### ISSUE TITLE
all metrics are zero

### ISSUE THREAD

**Issue by willsketch** [IrDIE/YOLO8_SAHI#3]
Hey, all the metrics i am getting are 0. Do you may be know why ?
I have evaluated my model without sahi and i get values for all the metrics. But this is what i get  for both the basic and sahi validation  
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:12<00:00,  6.34s/it]
                   all         32         89          0          0          0          0

**Comment by IrDIE** [comment]
You are saying two opposite things: 
1) "evaluated my model without sahi and i get values for all the metrics"
2) "get for basic .. validation zeros"

Can you explain? In the first case you validate model using base ultralitycs repo and values were not zero? 
@willsketch

**Comment by willsketch** [comment]
Hey thanks for the reply. The problem was on my end. I was using wrong labels. Everything works now :)
